version: '3'
services:
  app:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        PORT: ${PORT}
        HOST: ${HOST}
      dockerfile: Dockerfile
    env_file: .env
    user: ${UID}:${GID}
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - spraby_network

networks:
  spraby_network:
    external: true
